[package]
name = "dst"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
futures = "0.3.31"
rdkafka = "0.36.2"
redis = { version = "0.27.5", features = ["aio", "tokio-comp"] }
tokio = { version = "1.41.1", features = ["full", "fs"] }
